### ISSUE TITLE
ai ocp_install stage breaks on : The error was: 'dict object' has no attribute 'OPENSHIFT_VERSIONS'

### ISSUE THREAD

**Issue by pinikomarov** [openstack-k8s-operators/osp-director-dev-tools#255]
https://rhos-ci-staging-jenkins.lab.eng.tlv2.redhat.com/job/osp-director-dev-tools-ai-pr-custom-pkomarov/27/artifact/logs/01_ocp_install.sh.log
breaks on task : https://github.com/openstack-k8s-operators/osp-director-dev-tools/blob/ae0061a192e80821401560815f2fab89dbaa886c/ansible/ocp_ai_prep.yaml#L503

probably, (advices by Andrew)  this is because the upstream change in : 
https://raw.githubusercontent.com/openshift/assisted-service/master/onprem-environment

Where there is no OPENSHIFT_VERSIONS anymore

**Comment by abays** [comment]
Fixed by https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/256
